<a href="https://colab.research.google.com/github/Mohamad-Selawy/Data-Analysis/blob/main/Python/Pandas/numPy_for_numerical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Numerical Operations




NumPy (Numerical Python) is a core library in Python for working with numbers, especially large sets of numerical data. It introduces a powerful object called the `ndarray` (N-dimensional array), which is like a super-fast, flexible list designed for numbers. NumPy also provides many functions to perform quick operations on these arrays.

### Why Use NumPy for Data Analysis?

1.  **Speed**: NumPy operations are significantly faster than standard Python lists when dealing with numerical data. This speed comes from its foundation being written in C, which is crucial for big datasets and complex calculations.
2.  **Memory Efficiency**: NumPy arrays use less memory than Python lists, making it efficient for storing and processing large amounts of numerical data.
3.  **Powerful Functions**: It comes with a vast collection of functions for common mathematical operations, linear algebra, and statistical calculations, all optimized for performance.
4.  **Foundation for Other Libraries**: Many other essential data science libraries, including Pandas, SciPy, and Scikit-learn, are built using NumPy. This means that understanding NumPy helps you understand how these other tools work efficiently.

### NumPy vs. Pandas: A Simple Comparison

Both NumPy and Pandas are indispensable for data analysis, but they serve different, yet complementary, purposes:

*   **NumPy (The Numerical Engine)**:
    *   **What it does**: Focuses on fast, numerical computations using `ndarrays`. Think of it as the powerhouse for crunching numbers, especially when all data in an array is of the same type (homogeneous).
    *   **Best for**: Mathematical operations, scientific computing, and foundational numerical tasks where raw speed and efficiency are key.

*   **Pandas (The Data Organizer)**:
    *   **What it does**: Built on top of NumPy, Pandas provides higher-level data structures like `DataFrames` (like spreadsheets or SQL tables) and `Series` (like a single column from a table). These can handle mixed data types (heterogeneous data) and are designed for structured, tabular data.
    *   **Best for**: Data cleaning, manipulation, analysis, and working with real-world datasets that often have labels, missing values, and different types of information in columns.

**In short, NumPy gives you the fast, low-level tools for numerical data, while Pandas provides the more user-friendly, high-level structures to manage and analyze complex datasets, often using NumPy's capabilities behind the scenes.** Getting comfortable with NumPy is a solid step toward mastering data manipulation with Pandas.

## 2. Creating and Manipulating Arrays
NumPy arrays are more powerful than Python lists for numerical data.

### Explanations for Array Creation Methods

*   **`np.array()`**: This is the most general way to create an array. You pass it a Python list or tuple, and it converts it into a NumPy `ndarray`.
*   **`np.arange()`**: This function creates an array with evenly spaced values within a given interval. You specify the `start`, `stop`, and an optional `step` size.

In [ ]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

# Range of numbers
ar = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]

In [ ]:
print(a)
print(b)
print(ar)

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### 2.1 Checking Array Shape and Type

NumPy arrays have useful attributes to inspect their properties:

*   **`.shape`**: Returns a tuple representing the dimensions of the array. For a 1D array with 5 elements, it would be `(5,)`. For a 2D array with 2 rows and 3 columns, it would be `(2, 3)`.
*   **`.dtype`**: Returns the data type of the elements in the array (e.g., `int64`, `float64`). All elements in a NumPy array must have the same data type.
*   **`.ndim`**: Returns the number of dimensions of the array (e.g., 1 for a 1D array, 2 for a 2D array).

In [ ]:
# Using one of the previously created arrays, 'b'
print("Array b:\n", b)
print("Shape of b:", b.shape)
print("Number of dimensions of b (ndim):", b.ndim)
print("Data type of elements in b (dtype):", b.dtype)

# Using a 1D array 'a'
print("\nArray a:\n", a)
print("Shape of a:", a.shape)
print("Number of dimensions of a (ndim):", a.ndim)
print("Data type of elements in a (dtype):", a.dtype)

Array b:
 [[1 2]
 [3 4]]
Shape of b: (2, 2)
Number of dimensions of b (ndim): 2
Data type of elements in b (dtype): int64

Array a:
 [1 2 3]
Shape of a: (3,)
Number of dimensions of a (ndim): 1
Data type of elements in a (dtype): int64


## 3. Indexing, Slicing, and Reshaping

### Indexing and Slicing

### Explanation of Indexing and Slicing

NumPy arrays support various ways to access elements:

*   **Indexing**: You can access individual elements using their `[row, column]` index (for 2D arrays) or `[index]` (for 1D arrays). For example, `arr[0, 1]` gets the element at the first row and second column.
*   **Slicing**: You can extract sub-arrays using slices, similar to Python lists. The syntax is `[start:stop:step]`.
    *   `arr[:, 1]`: Selects all rows (`:` in the row dimension) and the second column (`1` in the column dimension). This extracts a column.
    *   `arr[1, :]`: Selects the second row (`1` in the row dimension) and all columns (`:` in the column dimension). This extracts a row.

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[0, 1])  # 20
print(arr[:, 1])  # column 1 -> [20, 50]
print(arr[1, :])  # row 1 -> [40, 50, 60]

20
[20 50]
[40 50 60]


### Reshaping

### Explanation of Reshaping

*   **`array.reshape(shape)`**: This method allows you to change the shape of an array without changing its data. You provide a new tuple representing the desired dimensions of the array. The total number of elements in the new shape must be the same as the original array. You can use `-1` for one of the dimensions, and NumPy will automatically calculate the correct size for that dimension.

In [ ]:
flat = np.array([1, 2, 3, 4, 5, 6])
reshaped = flat.reshape((2, 3))  # 2 rows, 3 columns
print(flat)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 4. Element-wise Operations
NumPy allows you to perform arithmetic on arrays directly.



### Explanation of Element-wise Operations

NumPy arrays allow for direct application of arithmetic operations (like addition, subtraction, multiplication, and division) to every element of the array. When you perform an operation between two arrays of the same shape, the operation is applied element by element.

*   **Array with Array**: If you add, subtract, multiply, or divide two arrays, the operation is performed between corresponding elements in each array, resulting in a new array of the same shape.
*   **Array with Scalar**: When an operation is performed between an array and a single number (scalar), the scalar value is applied to every element of the array.

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)    # [11, 22, 33]
print(x * 2)    # [2, 4, 6]
print(y / x)    # [10, 10, 10]

[11 22 33]
[2 4 6]
[10. 10. 10.]


Works the same way for 2D arrays.


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", arr1, '\n')
print("Array 2:\n", arr2)
print("\nAddition (arr1 + arr2):\n", arr1 + arr2)
print("\nMultiplication (arr1 * arr2):\n", arr1 * arr2)
print("\nScalar Multiplication (arr1 * 3):\n", arr1 * 3)

Array 1:
 [[1 2]
 [3 4]] 

Array 2:
 [[5 6]
 [7 8]]

Addition (arr1 + arr2):
 [[ 6  8]
 [10 12]]

Multiplication (arr1 * arr2):
 [[ 5 12]
 [21 32]]

Scalar Multiplication (arr1 * 3):
 [[ 3  6]
 [ 9 12]]


## 5. Aggregations: Mean, Median, Std Dev
NumPy provides fast aggregation functions:


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Basic aggregations
print("Mean:", arr.mean())         # Mean of all elements
print("Row-wise Mean:", arr.mean(axis=1))  # [20, 50]
print("Column-wise Mean:", arr.mean(axis=0))  # [25, 35, 45]

# Median
print("Median:", np.median(arr))

# Standard deviation
print("Std Dev:", np.std(arr))

Mean: 35.0
Row-wise Mean: [20. 50.]
Column-wise Mean: [25. 35. 45.]
Median: 35.0
Std Dev: 17.07825127659933


## Summary

| Concept      | Function                                |
| ------------ | --------------------------------------- |
| Create array | `np.array()` |
| Index/Slice  | `arr[1, 2]`, `arr[:, 0]`                |
| Reshape      | `arr.reshape()`                         |
| Arithmetic   | `+`, `-`, `*`, `/`                      |
| Aggregations | `mean()`, `std()`, `median()`           |




## Exercises

### Exercise 1: Array Creation and Properties

1.  Create a 1D NumPy array named `data_1d` containing the numbers 5, 10, 15, 20, 25.
2.  Print the array and its `shape`, `ndim` (number of dimensions), and `dtype` (data type).
3.  Create a 2D NumPy array named `data_2d` of shape (3, 4) with all elements initialized to 7.
4.  Print `data_2d` and its `shape`.

### Exercise 2: Indexing, Slicing, and Reshaping

Given the array `matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`:

1.  Access and print the element in the second row, third column.
2.  Slice the array to get the first two rows and all columns.
3.  Slice the array to get all rows and the last column.
4.  Reshape the `matrix` into a 4x3 array named `reshaped_matrix` and print it.